-- MySQL Script generated by MySQL Workbench
-- Thu May 10 16:00:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Foodboard
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Foodboard
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Foodboard` DEFAULT CHARACTER SET utf8 ;
USE `Foodboard` ;

-- -----------------------------------------------------
-- Table `Foodboard`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Foodboard`.`Users` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL COMMENT 'Holds contact first name',
  `lastName` VARCHAR(45) NOT NULL COMMENT 'Holds user last name',
  `email` VARCHAR(45) NOT NULL COMMENT 'Holds user email\n',
  `suiteNumber` INT(10) NOT NULL COMMENT 'Holds user\'s apartment suite number\n',
  `password` VARCHAR(61) NOT NULL COMMENT 'Holds user\'s password\n',
  `createdAt` DATETIME NOT NULL COMMENT 'Holds creation time of the user',
  `updatedAt` DATETIME NOT NULL COMMENT 'Holds the time the user last updated',
  `role` TINYINT NOT NULL DEFAULT 0 COMMENT 'Stores the role of the user\nAdmin = 0, User = 1\n',
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Foodboard`.`FoodItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Foodboard`.`FoodItem` (
  `itemID` INT NOT NULL AUTO_INCREMENT,
  `foodName` VARCHAR(45) NOT NULL COMMENT 'Holds the name of the food item\n',
  `foodDescription` VARCHAR(255) NOT NULL COMMENT 'Holds the description of the item (time of pickup, description)',
  `foodGroup` VARCHAR(45) NOT NULL COMMENT 'Holds the food group of the item',
  `foodExpiryTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Holds the expiry date of the food item\n',
  `foodImage` VARCHAR(255) NOT NULL COMMENT 'Holds the image of the food item\n',
  PRIMARY KEY (`itemID`));


-- -----------------------------------------------------
-- Table `Foodboard`.`Posting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Foodboard`.`Posting` (
  `postID` INT NOT NULL AUTO_INCREMENT,
  `FoodItem_ItemID` INT NOT NULL,
  `Users_UserID` INT NOT NULL,
  `claimStatus` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`postID`, `FoodItem_ItemID`, `Users_UserID`),
  INDEX `fk_Posting_FoodItem1_idx` (`FoodItem_ItemID` ASC),
  INDEX `fk_Posting_Users1_idx` (`Users_UserID` ASC),
  CONSTRAINT `fk_Posting_FoodItem1`
    FOREIGN KEY (`FoodItem_ItemID`)
    REFERENCES `Foodboard`.`FoodItem` (`itemID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Posting_Users1`
    FOREIGN KEY (`Users_UserID`)
    REFERENCES `Foodboard`.`Users` (`userID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Foodboard`.`Board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Foodboard`.`Board` (
  `boardPostID` INT NOT NULL AUTO_INCREMENT,
  `userPostClaimed` TINYINT NULL DEFAULT 0,
  `Posting_PostID` INT NOT NULL,
  PRIMARY KEY (`boardPostID`, `Posting_PostID`),
  INDEX `fk_FoodboardBoard_Posting_idx` (`Posting_PostID` ASC),
  CONSTRAINT `fk_FoodboardBoard_Posting`
    FOREIGN KEY (`Posting_PostID`)
    REFERENCES `Foodboard`.`Posting` (`postID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Foodboard`.`UserList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Foodboard`.`UserList` (
  `listingID` INT NOT NULL AUTO_INCREMENT,
  `Users_UserID` INT NOT NULL,
  PRIMARY KEY (`listingID`, `Users_UserID`),
  INDEX `fk_UserList_Users1_idx` (`Users_UserID` ASC),
  CONSTRAINT `fk_UserList_Users1`
    FOREIGN KEY (`Users_UserID`)
    REFERENCES `Foodboard`.`Users` (`userID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Foodboard`.`Sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Foodboard`.`Sessions` (
  `sessionID` VARCHAR(255) NOT NULL,
  `Users_userID` INT NOT NULL,
  PRIMARY KEY (`sessionID`, `Users_userID`),
  INDEX `fk_Sessions_Users1_idx` (`Users_userID` ASC),
  CONSTRAINT `fk_Sessions_Users1`
    FOREIGN KEY (`Users_userID`)
    REFERENCES `Foodboard`.`Users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
